app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/[database_name]
    username: [username]
    password: [password]
    pool-size: [number of allowed requests until a new db connection]